language: node_js
sudo: false
node_js:
  - "4"
  - "6"
  - "7"
  - "node"
before_script:
  - npm install -g gulp
  - wget https://gitlab.filiosoft.com/oss/polr-mobile/raw/master/config.xml
script: 
  - gulp test
