language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "2"
  - "3"
  - "4"
  - "6"
  - "7"
  - "node"
before_script:
  - npm install -g gulp
  - wget https://gitlab.filiosoft.com/filiosoft-osp/polr-mobile/raw/master/config.xml
script: 
  - gulp test
after_success:
  - git clone --bare https://nprail:$GITHUB_ACCESS_KEY@github.com/Filiosoft/scv-cli.git
  - cd scv-cli.git
  - git push --mirror https://nprail:$GITLAB_ACCESS_KEY@gitlab.filiosoft.com/filiosoft-oss/scv-cli.git
