language: node_js
sudo: false
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "2"
  - "3"
  - "4"
  - "node"
before_script:
  - npm install -g
  - wget https://gitlab.filiosoft.com/filiosoft-osp/polr-mobile/raw/master/config.xml
script: 
  - scv --help
  - scv --version
  - scv 1.4.5 455