language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "2"
  - "3"
  - "4"
  - "node"
before_script:
  - npm install -g gulp
  - wget https://gitlab.filiosoft.com/filiosoft-osp/polr-mobile/raw/master/config.xml
script: 
  - gulp test
